name: dynamic_form_engine_example
description: "Interactive Web Showcase for the Dynamic Form Engine Flutter Package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_form_engine:
    path: ../
  geolocator: ^14.0.3
  file_picker: ^13.1.0
  image_picker: ^1.2.3
  share_plus: ^13.3.0
  archive: ^3.6.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
